# Generated by Django 4.2.4 on 2023-08-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='нет опсания', max_length=200),
            preserve_default=False,
        ),
    ]
